site_name: Event Check-In
repo_url: https://github.com/systopia/de.systopia.eventcheckin
edit_uri: https://github.com/systopia/de.systopia.eventcheckin_de/edit/master/docs
site_description: 'Eine Anleitung für die Event-Check-In-Erweiterung.'
site_author: 'SYSTOPIA'
theme:
  name:
    material

nav:
  - Startseite: index.md
  - Installation und technische Informationen: installation-technical-information.md
  - Konfiguration: configuration.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.highlight:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: de
